// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElPagination: typeof import('element-plus/es')['ElPagination']
  const ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
}
export {}
